// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeTile.Storage.Contexts;

#nullable disable

namespace TimeTile.Storage.Migrations
{
    [DbContext(typeof(TimetileDbContext))]
    [Migration("20250705175155_FileDoesNotAlsoBelongToCourse")]
    partial class FileDoesNotAlsoBelongToCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeTile.Core.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("ClassroomTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_type_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomTypeId");

                    b.HasIndex("InstitutionId", "Title", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("classrooms_institution_title_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("InstitutionId", "Title", "DeletedAt"), false);

                    b.ToTable("classrooms", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Classroom_Title_Valid", "\"title\" ~ '^[A-Za-z0-9\\s\\-.,_&()]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.ClassroomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<int?>("IconId")
                        .HasColumnType("integer")
                        .HasColumnName("icon_id");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IconId")
                        .IsUnique();

                    b.HasIndex("InstitutionId");

                    b.HasIndex("Description", "InstitutionId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("classroom_types_description_institution_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Description", "InstitutionId", "DeletedAt"), false);

                    b.ToTable("classroom_types", (string)null);
                });

            modelBuilder.Entity("TimeTile.Core.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("IconId")
                        .HasColumnType("integer")
                        .HasColumnName("icon_id");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsAdvanced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_advanced");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<int>("TermId")
                        .HasColumnType("integer")
                        .HasColumnName("term_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IconId")
                        .IsUnique();

                    b.HasIndex("InstitutionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TermId");

                    b.HasIndex("Title", "SubjectId", "TeacherId", "InstitutionId", "TermId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("courses_title_subject_teacher_institution_term_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Title", "SubjectId", "TeacherId", "InstitutionId", "TermId", "DeletedAt"), false);

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Course_Title_Valid", "\"title\"  ~ '^[A-Za-z0-9\\s\\-.,_&()]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.CourseToStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("ExamGradeId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_grade_id");

                    b.Property<bool>("HasExam")
                        .HasColumnType("boolean")
                        .HasColumnName("has_exam");

                    b.Property<short>("PositionX")
                        .HasColumnType("smallint")
                        .HasColumnName("position_x");

                    b.Property<short>("PositionY")
                        .HasColumnType("smallint")
                        .HasColumnName("position_y");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ExamGradeId")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.HasIndex("CourseId", "StudentId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("courses_students_course_student_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CourseId", "StudentId", "DeletedAt"), false);

                    b.ToTable("courses_students", null, t =>
                        {
                            t.HasCheckConstraint("CK_CoursesStudents_HasExam_ExamGrade", "\"has_exam\" = TRUE OR \"exam_grade_id\" IS NULL");

                            t.HasCheckConstraint("CK_CoursesStudents_PositionX_Positive", "\"position_x\" >= 0");

                            t.HasCheckConstraint("CK_CoursesStudents_PositionY_Positive", "\"position_y\" >= 0");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extension");

                    b.Property<Guid>("FileGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("file_guid");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_name");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("FileGuid")
                        .IsUnique()
                        .HasDatabaseName("files_file_guid_key");

                    b.HasIndex("StoragePath", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("files_storage_path_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("StoragePath", "DeletedAt"), false);

                    b.ToTable("files", null, t =>
                        {
                            t.HasCheckConstraint("CHK_File_Extension_Valid", "LOWER(\"extension\") IN ('pdf', 'docx', 'xlsx', 'png', 'jpg', 'jpeg', 'txt', 'zip')");

                            t.HasCheckConstraint("CHK_File_File_Guid_Valid", "\"storage_path\" LIKE '%' || \"file_guid\"::text || '.%'");

                            t.HasCheckConstraint("CHK_File_Size_Valid", "\"size\" > 0");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.Property<float>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f)
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("grades", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Grade_Type_Valid", "LOWER(\"type\") IN ('classwork', 'homework', 'exam')");

                            t.HasCheckConstraint("CHK_Grade_Value_Positive", "\"value\" > 0");

                            t.HasCheckConstraint("CHK_Grade_Weight_Positive", "\"weight\" > 0");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Title", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("groups_institution_title_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("InstitutionId", "Title", "DeletedAt"), false);

                    b.ToTable("groups", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Group_Title_Valid", "\"title\"  ~ '^[A-Za-z0-9\\s\\-.,_&()]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("institutions_domain_deleted_at_constraint");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Domain", "DeletedAt"), false);

                    b.HasIndex("Email", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("institutions_email_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Email", "DeletedAt"), false);

                    b.HasIndex("Title", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("institutions_title_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Title", "DeletedAt"), false);

                    b.ToTable("institutions", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Institution_Address_NotEmpty", "\"address\" ~ '^[[:alpha:]\\d\\s''.,#/()-]+$'");

                            t.HasCheckConstraint("CHK_Institution_Domain_Valid", "\"domain\" ~ '^(?:[[:alpha:]0-9-]{1,63}\\.)+[A-Za-z]{2,}$'");

                            t.HasCheckConstraint("CHK_Institution_Email_Valid", "\"email\" ~ '^(?!\\.)[A-Za-z0-9._%+-]+(?<!\\.)@[A-Za-z0-9-]+(?:\\.[A-Za-z0-9-]+)*\\.[A-Za-z]{2,}$'");

                            t.HasCheckConstraint("CHK_Institution_Phone_Valid", "\"phone_number\" ~ '^\\+[1-9]\\d{6,14}$'");

                            t.HasCheckConstraint("CHK_Institution_Title_NotEmpty", "\"title\" ~ '^[A-Za-z0-9\\s\\-.,_&()]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.InstitutionMemberToGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("InstitutionMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_member_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("InstitutionMemberId", "GroupId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("institution_members_groups_institution_member_group_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("InstitutionMemberId", "GroupId", "DeletedAt"), false);

                    b.ToTable("institution_members_groups", (string)null);
                });

            modelBuilder.Entity("TimeTile.Core.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("classroom_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("HomeworkDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("homework_description");

                    b.Property<int>("LessonStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_status_id");

                    b.Property<int>("TimetableUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("timetable_unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("LessonStatusId");

                    b.HasIndex("TimetableUnitId");

                    b.HasIndex("CourseId", "TimetableUnitId", "Date", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("lessons_course_timetable_date_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CourseId", "TimetableUnitId", "Date", "DeletedAt"), false);

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("TimeTile.Core.Models.LessonStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArgbColor")
                        .HasColumnType("integer")
                        .HasColumnName("argb_color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("Description", "InstitutionId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("lesson_statuses_description_institution_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Description", "InstitutionId", "DeletedAt"), false);

                    b.ToTable("lesson_statuses", null, t =>
                        {
                            t.HasCheckConstraint("CHK_LessonStatus_Description_Valid", "\"description\"  ~ '^[[:alpha:]\\d\\s.,!?]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.LessonToStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CameAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("came_at");

                    b.Property<int?>("ClassworkGradeId")
                        .HasColumnType("integer")
                        .HasColumnName("classwork_grade_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("HomeworkGradeId")
                        .HasColumnType("integer")
                        .HasColumnName("homework_grade_id");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("time with time zone")
                        .HasColumnName("left_at");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ClassworkGradeId")
                        .IsUnique();

                    b.HasIndex("HomeworkGradeId")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.HasIndex("LessonId", "StudentId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("lessons_students_lesson_student_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("LessonId", "StudentId", "DeletedAt"), false);

                    b.ToTable("lessons_students", null, t =>
                        {
                            t.HasCheckConstraint("CHK_LessonToStudent_CameAt_IsNotNull_OR_CameAt_LeftAt_IsNull", "(\"came_at\" IS NULL AND \"left_at\" IS NULL) OR (\"came_at\" IS NOT NULL)");

                            t.HasCheckConstraint("CHK_LessonToStudent_CameAt_LessThan_LeftAt", "(\"came_at\" < \"left_at\") OR (\"left_at\" IS NULL)");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Description", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("permissions_description_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Description", "DeletedAt"), false);

                    b.ToTable("permissions", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Permission_Description_Valid", "\"description\"  ~ '^[[:alpha:]\\d\\s.,!?]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("ReplaceTokenId")
                        .HasColumnType("integer")
                        .HasColumnName("replace_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReplaceTokenId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("refresh_tokens_token_constraint");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Token"), false);

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("refresh_tokens_user_revoked_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TimeTile.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Title", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("roles_title_institution_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("InstitutionId", "Title", "DeletedAt"), false);

                    b.ToTable("roles", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Role_Title_Valid", "\"title\"  ~ '^[A-Za-z0-9\\s\\-.,_&()]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.RoleToPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("roles_permissions_role_permission_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("RoleId", "PermissionId", "DeletedAt"), false);

                    b.ToTable("roles_permissions", (string)null);
                });

            modelBuilder.Entity("TimeTile.Core.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("Title", "InstitutionId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("subjects_title_institution_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Title", "InstitutionId", "DeletedAt"), false);

                    b.ToTable("subjects", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Subject_Title_Valid", "\"title\" ~ '^[A-Za-z0-9\\s\\-.,_&()]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.TeacherToSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("teachers_subjects_teacher_subject_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TeacherId", "SubjectId", "DeletedAt"), false);

                    b.ToTable("teachers_subjects", (string)null);
                });

            modelBuilder.Entity("TimeTile.Core.Models.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Title", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("terms_institution_title_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("InstitutionId", "Title", "DeletedAt"), false);

                    b.HasIndex("StartDate", "EndDate", "InstitutionId", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("terms_institution_start_end_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("StartDate", "EndDate", "InstitutionId", "DeletedAt"), false);

                    b.ToTable("terms", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Term_StartDate_LessThan_EndDate", "\"start_date\" < \"end_date\"");

                            t.HasCheckConstraint("CHK_Term_Title_Valid", "\"title\" ~ '^[A-Za-z0-9\\s\\-.,_&()]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.TimetableUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("time with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("time with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "Title", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("timetable_units_institution_title_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("InstitutionId", "Title", "DeletedAt"), false);

                    b.HasIndex("InstitutionId", "StartTime", "EndTime", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("timetable_units_institution_start_end_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("InstitutionId", "StartTime", "EndTime", "DeletedAt"), false);

                    b.ToTable("timetable_units", null, t =>
                        {
                            t.HasCheckConstraint("CHK_TimetableUnit_StartTime_LessThan_EndTime", "\"start_time\" < \"end_time\"");

                            t.HasCheckConstraint("CHK_TimetableUnit_Title_Valid", "\"title\" ~ '^[A-Za-z0-9\\s\\-.,_&()]+$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarId")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("home_address");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId")
                        .IsUnique();

                    b.HasIndex("InstitutionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Login", "DeletedAt")
                        .IsUnique()
                        .HasDatabaseName("users_login_deleted_at_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Login", "DeletedAt"), false);

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CHK_User_BirthDate_Valid", "\"birth_date\" <= NOW()");

                            t.HasCheckConstraint("CHK_User_Firstname_Valid", "\"firstname\" ~ '^[[:alpha:]]+(?:[\\s''-][[:alpha:]]+)*$'");

                            t.HasCheckConstraint("CHK_User_HomeAddress_Valid", "\"home_address\" ~ '^[[:alpha:]\\d\\s''.,#/()-]+$'");

                            t.HasCheckConstraint("CHK_User_Lastname_Valid", "\"lastname\" ~ '^[[:alpha:]]+(?:[\\s''-][[:alpha:]]+)*$'");

                            t.HasCheckConstraint("CHK_User_Login_Valid", "\"login\" ~ '^(?!\\.)[A-Za-z0-9._%+-]+(?<!\\.)@[A-Za-z0-9-]+(?:\\.[A-Za-z0-9-]+)*\\.[A-Za-z]{2,}$'");

                            t.HasCheckConstraint("CHK_User_PhoneNumber_Valid", "\"phone_number\" ~ '^\\+[1-9]\\d{6,14}$'");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TimeTile.Core.Models.InstitutionMember", b =>
                {
                    b.HasBaseType("TimeTile.Core.Models.User");

                    b.Property<int?>("PreferredClassroomId")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_classroom_id");

                    b.Property<int>("WeekWorkHours")
                        .HasColumnType("integer")
                        .HasColumnName("week_work_hours");

                    b.HasIndex("PreferredClassroomId");

                    b.ToTable("institution_members", null, t =>
                        {
                            t.HasCheckConstraint("CHK_User_BirthDate_Valid", "\"birth_date\" <= NOW()");

                            t.HasCheckConstraint("CHK_User_Firstname_Valid", "\"firstname\" ~ '^[[:alpha:]]+(?:[\\s''-][[:alpha:]]+)*$'");

                            t.HasCheckConstraint("CHK_User_HomeAddress_Valid", "\"home_address\" ~ '^[[:alpha:]\\d\\s''.,#/()-]+$'");

                            t.HasCheckConstraint("CHK_User_Lastname_Valid", "\"lastname\" ~ '^[[:alpha:]]+(?:[\\s''-][[:alpha:]]+)*$'");

                            t.HasCheckConstraint("CHK_User_Login_Valid", "\"login\" ~ '^(?!\\.)[A-Za-z0-9._%+-]+(?<!\\.)@[A-Za-z0-9-]+(?:\\.[A-Za-z0-9-]+)*\\.[A-Za-z]{2,}$'");

                            t.HasCheckConstraint("CHK_User_PhoneNumber_Valid", "\"phone_number\" ~ '^\\+[1-9]\\d{6,14}$'");

                            t.HasCheckConstraint("CK_InstitutionMember_WeekWorkHours_Positive", "\"week_work_hours\" > 0");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.Student", b =>
                {
                    b.HasBaseType("TimeTile.Core.Models.User");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.HasIndex("GroupId");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("CHK_User_BirthDate_Valid", "\"birth_date\" <= NOW()");

                            t.HasCheckConstraint("CHK_User_Firstname_Valid", "\"firstname\" ~ '^[[:alpha:]]+(?:[\\s''-][[:alpha:]]+)*$'");

                            t.HasCheckConstraint("CHK_User_HomeAddress_Valid", "\"home_address\" ~ '^[[:alpha:]\\d\\s''.,#/()-]+$'");

                            t.HasCheckConstraint("CHK_User_Lastname_Valid", "\"lastname\" ~ '^[[:alpha:]]+(?:[\\s''-][[:alpha:]]+)*$'");

                            t.HasCheckConstraint("CHK_User_Login_Valid", "\"login\" ~ '^(?!\\.)[A-Za-z0-9._%+-]+(?<!\\.)@[A-Za-z0-9-]+(?:\\.[A-Za-z0-9-]+)*\\.[A-Za-z]{2,}$'");

                            t.HasCheckConstraint("CHK_User_PhoneNumber_Valid", "\"phone_number\" ~ '^\\+[1-9]\\d{6,14}$'");
                        });
                });

            modelBuilder.Entity("TimeTile.Core.Models.Classroom", b =>
                {
                    b.HasOne("TimeTile.Core.Models.ClassroomType", "ClassroomType")
                        .WithMany("Classrooms")
                        .HasForeignKey("ClassroomTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("classrooms_classroom_type_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("Classrooms")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("classrooms_institution_id_fkey");

                    b.Navigation("ClassroomType");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("TimeTile.Core.Models.ClassroomType", b =>
                {
                    b.HasOne("TimeTile.Core.Models.File", "Icon")
                        .WithOne("ClassroomType")
                        .HasForeignKey("TimeTile.Core.Models.ClassroomType", "IconId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("classroom_types_icon_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("ClassroomTypes")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("classroom_types_institution_id_fkey");

                    b.Navigation("Icon");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Course", b =>
                {
                    b.HasOne("TimeTile.Core.Models.File", "Icon")
                        .WithOne("Course")
                        .HasForeignKey("TimeTile.Core.Models.Course", "IconId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("courses_icon_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("Courses")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("courses_institution_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("courses_subject_id_fkey");

                    b.HasOne("TimeTile.Core.Models.InstitutionMember", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("courses_teacher_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Term", "Term")
                        .WithMany("Courses")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("courses_term_id_fkey");

                    b.Navigation("Icon");

                    b.Navigation("Institution");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("TimeTile.Core.Models.CourseToStudent", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Course", "Course")
                        .WithMany("CoursesToStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("courses_students_course_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Grade", "ExamGrade")
                        .WithOne("CourseToStudent")
                        .HasForeignKey("TimeTile.Core.Models.CourseToStudent", "ExamGradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("courses_students_exam_grade_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Student", "Student")
                        .WithMany("CoursesToStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("courses_students_student_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("ExamGrade");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Group", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("Groups")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("groups_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("TimeTile.Core.Models.InstitutionMemberToGroup", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Group", "Group")
                        .WithMany("InstitutionMembersToGroup")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("institution_members_groups_group_id_fkey");

                    b.HasOne("TimeTile.Core.Models.InstitutionMember", "InstitutionMember")
                        .WithMany("InstitutionMemberToGroups")
                        .HasForeignKey("InstitutionMemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("institution_members_groups_institution_member_id_fkey");

                    b.Navigation("Group");

                    b.Navigation("InstitutionMember");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Lesson", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Classroom", "Classroom")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("lessons_classroom_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("lessons_course_id_fkey");

                    b.HasOne("TimeTile.Core.Models.LessonStatus", "LessonStatus")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("lessons_lesson_status_id_fkey");

                    b.HasOne("TimeTile.Core.Models.TimetableUnit", "TimetableUnit")
                        .WithMany("Lessons")
                        .HasForeignKey("TimetableUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("lessons_timetable_unit_id_fkey");

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("LessonStatus");

                    b.Navigation("TimetableUnit");
                });

            modelBuilder.Entity("TimeTile.Core.Models.LessonStatus", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("LessonStatuses")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("lesson_statuses_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("TimeTile.Core.Models.LessonToStudent", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Grade", "ClassworkGrade")
                        .WithOne("LessonToStudentClasswork")
                        .HasForeignKey("TimeTile.Core.Models.LessonToStudent", "ClassworkGradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("lessons_students_classwork_grade_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Grade", "HomeworkGrade")
                        .WithOne("LessonToStudentHomework")
                        .HasForeignKey("TimeTile.Core.Models.LessonToStudent", "HomeworkGradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("lessons_students_homework_grade_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Lesson", "Lesson")
                        .WithMany("LessonsToStudents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("lessons_students_lesson_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Student", "Student")
                        .WithMany("LessonsToStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("lessons_students_student_id_fkey");

                    b.Navigation("ClassworkGrade");

                    b.Navigation("HomeworkGrade");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TimeTile.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("TimeTile.Core.Models.RefreshToken", "ReplaceToken")
                        .WithMany()
                        .HasForeignKey("ReplaceTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("refresh_tokens_replace_token_id_fkey");

                    b.HasOne("TimeTile.Core.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("ReplaceToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Role", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("Roles")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("roles_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("TimeTile.Core.Models.RoleToPermission", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Permission", "Permission")
                        .WithMany("RolesToPermission")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("roles_permissions_permission_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Role", "Role")
                        .WithMany("RoleToPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("roles_permissions_role_id_fkey");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Subject", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("Subjects")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("subjects_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("TimeTile.Core.Models.TeacherToSubject", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Subject", "Subject")
                        .WithMany("TeachersToSubject")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("teachers_subjects_subject_id_fkey");

                    b.HasOne("TimeTile.Core.Models.InstitutionMember", "Teacher")
                        .WithMany("TeacherToSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("teachers_subjects_teacher_id_fkey");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Term", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("Terms")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("terms_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("TimeTile.Core.Models.TimetableUnit", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("TimetableUnits")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("timetable_units_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("TimeTile.Core.Models.User", b =>
                {
                    b.HasOne("TimeTile.Core.Models.File", "Avatar")
                        .WithOne("User")
                        .HasForeignKey("TimeTile.Core.Models.User", "AvatarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("users_avatar_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("users_institution_id_fkey");

                    b.HasOne("TimeTile.Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Avatar");

                    b.Navigation("Institution");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TimeTile.Core.Models.InstitutionMember", b =>
                {
                    b.HasOne("TimeTile.Core.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TimeTile.Core.Models.InstitutionMember", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeTile.Core.Models.Classroom", "Classroom")
                        .WithMany("InstitutionMembers")
                        .HasForeignKey("PreferredClassroomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("institution_members_preferred_classroom_id_fkey");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Student", b =>
                {
                    b.HasOne("TimeTile.Core.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("students_group_id_fkey");

                    b.HasOne("TimeTile.Core.Models.User", null)
                        .WithOne()
                        .HasForeignKey("TimeTile.Core.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Classroom", b =>
                {
                    b.Navigation("InstitutionMembers");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TimeTile.Core.Models.ClassroomType", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Course", b =>
                {
                    b.Navigation("CoursesToStudents");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TimeTile.Core.Models.File", b =>
                {
                    b.Navigation("ClassroomType");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Grade", b =>
                {
                    b.Navigation("CourseToStudent");

                    b.Navigation("LessonToStudentClasswork");

                    b.Navigation("LessonToStudentHomework");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Group", b =>
                {
                    b.Navigation("InstitutionMembersToGroup");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Institution", b =>
                {
                    b.Navigation("ClassroomTypes");

                    b.Navigation("Classrooms");

                    b.Navigation("Courses");

                    b.Navigation("Groups");

                    b.Navigation("LessonStatuses");

                    b.Navigation("Roles");

                    b.Navigation("Subjects");

                    b.Navigation("Terms");

                    b.Navigation("TimetableUnits");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Lesson", b =>
                {
                    b.Navigation("LessonsToStudents");
                });

            modelBuilder.Entity("TimeTile.Core.Models.LessonStatus", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Permission", b =>
                {
                    b.Navigation("RolesToPermission");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Role", b =>
                {
                    b.Navigation("RoleToPermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Subject", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("TeachersToSubject");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Term", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("TimeTile.Core.Models.TimetableUnit", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TimeTile.Core.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("TimeTile.Core.Models.InstitutionMember", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("InstitutionMemberToGroups");

                    b.Navigation("TeacherToSubjects");
                });

            modelBuilder.Entity("TimeTile.Core.Models.Student", b =>
                {
                    b.Navigation("CoursesToStudents");

                    b.Navigation("LessonsToStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
